### ISSUE TITLE
About poap script execution failed - poap.py

### ISSUE THREAD

**Issue by collinwqm** [chrisbog/Cisco-POAP#1]
Hi Chris Bogdon:

I used the poap.ap script you provided. The content that needs to be modified was modified according to your prompts, but when executing the script said poap script execution failed, Would you take a look when you get time and give me a hint, I'd really appreciate.

Here is modified infor on script:
################################
n9k_image_version       = "nxos.7.0.3.I7.6.bin" # this must match your code version
image_dir_src           = "/home/vsftpd"  # Sample - /Users/bob/poap
ftp_image_dir_src_root  = image_dir_src
tftp_image_dir_src_root = image_dir_src
n9k_system_image_src    = "n9000-dk9.%s.bin" % n9k_image_version
config_file_src         = "/home/vsftpd/conf" # Sample - /Users/bob/poap/conf
image_dir_dst           = "bootflash:" # directory where n9k image will be stored
system_image_dst        = n9k_system_image_src
config_file_dst         = "volatile:poap.cfg"
md5sum_ext_src          = "md5"
# Required space on /bootflash (for config and system images)
required_space          = 450000

# copy protocol to download images and config
# options are: scp/http/tftp/ftp/sftp
protocol                = "ftp" # protocol to use to download images/config

# Host name and user credentials
username                = "ftpuser" # server account
ftp_username            = "ftpuser" # server account
password                = "ftpuser" # password
hostname                = "10.16.240.5" # ip address of ftp/scp/http/sftp server
####################################
Here is error log infor:
#####################################
INFO: free space is 51083112 kB
CLI : terminal dont-ask ; terminal password ftpuser ; copy ftp://ftpuser@10.16.240.5/n9000-dk9.nxos.7.0.3.I7.3.bin.bin.md5 volatile:n9000-dk9.nxos.7.0.3.I7.3.bin.bin.md5.poap_md5 vrf default
WARN: Copy Failed: 'Failed to open file.\n\n***** Transfer of file aborted, file not found or Login failed*****\nError during copy\n***** Transfer of file aborted *****\n'
INFO: Different source and destination images
CLI : terminal dont-ask ; terminal password ftpuser ; copy ftp://ftpuser@10.16.240.5/n9000-dk9.nxos.7.0.3.I7.3.bin.bin bootflash:.new/n9000-dk9.nxos.7.0.3.I7.3.bin.bin vrf default
WARN: Copy Failed: 'Failed to open file.\n\n***** Transfer of file aborted, file not found or Login failed*****\nError during copy\n***** Transfer of file aborted *****\n'
ERR : aborting
INFO: cleaning up
########################################
Good day.

**Comment by chrisbog** [comment]
When you enter the file name in the script, do not add the .bin.   My script will automatically add the .bin.

See:

CLI : terminal dont-ask ; terminal password ftpuser ; copy ftp://ftpuser@10.16.240.5/n9000-dk9.nxos.7.0.3.I7.3.bin.bin bootflash:.new/n9000-dk9.nxos.7.0.3.I7.3.bin.bin vrf default

It looks like the file it is trying to copy is:
ftp://ftpuser@10.16.240.5/n9000-dk9.nxos.7.0.3.I7.3.bin.bin

I'm assuming that is incorrect.

**Comment by collinwqm** [comment]
Thank you for your guidance, the problem is really what you said, almost no one here is using the poap function, so thank you for helping me solve this problem, really appreciated it.
